name: Build checks

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: Lint / Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier
        run: yarn prettier --check .
      - name: Build project
        run: yarn build
